version: '2'
services:
  speedtest:
    image: ouster/speedtest-for-influxdb-and-grafana
    container_name: speedtest
    volumes:
      - ./config.ini:/src/config.ini
    restart: always
    network: host
